### ISSUE TITLE
'note' field produces double output with @manual type

### ISSUE THREAD

**Issue by drgibbon** [plk/biblatex-apa#96]
Fully updated TeX Live 2019 here with biblatex-apa 9.6 (according to `\listfiles` output).

I'm trying to cite an R package with a `@manual` type citation (in `apa7` document class). The biblatex code is:
```
@Manual{Torchiano2020,
  author    = {Marco Torchiano},
  date      = {2020},
  title     = {Effsize -- A Package For Efficient Effect Size Computation},
  doi       = {10.5281/zenodo.1480624},
  note      = {R package version 0.7.9},
  publisher = {Zenodo},
}
```
The output includes the `note` field twice though:
> Torchiano, M. (2020). Effsize – a package for efficient effect size computation [R package version 0.7.9]. R package version 0.7.9. Zenodo. https://doi.org/10.5281/zenodo.1480624

**Comment by plk** [comment]
This is already fixed in version 8.3 of the apa6 package which you can update using the texlive manager.

**Comment by moewew** [comment]
I still get the issue with `apa` v9.6. The problem is not limited to `@manual`, there are more drivers with `\printfield{manual}` in the driver.
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=apa, backend=biber]{biblatex}


\begin{filecontents}{\jobname.bib}
@manual{torchiano,
  author    = {Marco Torchiano},
  date      = {2020},
  title     = {Effsize -- A Package For Efficient Effect Size Computation},
  doi       = {10.5281/zenodo.1480624},
  note      = {R package version 0.7.9},
  publisher = {Zenodo},
}
@incollection{brandt,
  author       = {von Brandt, Ahasver and Erich Hoffmann},
  editor       = {Ferdinand Seibt},
  title        = {Die nordischen L{\"a}nder von der Mitte des 11.~Jahrhunderts
                  bis 1448},
  date         = 1987,
  booktitle    = {Europa im Hoch- und Sp{\"a}tmittelalter},
  series       = {Handbuch der europ{\"a}ischen Geschichte},
  number       = 2,
  publisher    = {Klett-Cotta},
  location     = {Stuttgart},
  pages        = {884-917},
  note         = {LOREM},
  langid       = {german},
}
@inbook{kant:kpv,
  title        = {Kritik der praktischen Vernunft},
  date         = 1968,
  author       = {Kant, Immanuel},
  booktitle    = {Kritik der praktischen Vernunft. Kritik der Urtheilskraft},
  bookauthor   = {Kant, Immanuel},
  maintitle    = {Kants Werke. Akademie Textausgabe},
  volume       = 5,
  publisher    = {Walter de Gruyter},
  location     = {Berlin},
  pages        = {1-163},
  shorthand    = {KpV},
  note         = {DOLOR},
  langid       = {german},
}
\end{filecontents}
\addbibresource{\jobname.bib}
\addbibresource{biblatex-examples.bib}


\begin{document}
\cite{brandt,torchiano,kant:kpv}
\printbibliography
\end{document}
```

**Comment by plk** [comment]
Ah, I was looking at `apa6` as the version mentioned was 8.x ...

**Comment by drgibbon** [comment]
> Ah, I was looking at `apa6` as the version mentioned was 8.x ...

Sorry, I thought I was running 8.2 (the version number written in the locally installed manual PDF), but I checked it with `\listfiles` and it's 9.6. I'm also using the `apa7` document class.

**Comment by plk** [comment]
Should be fixed in Git master branch for `biblatex-apa`.

**Comment by drgibbon** [comment]
@plk Awesome, thank you!
